/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     29-11-2015 2:45:15                           */
/*==============================================================*/


ALTER TABLE IMMOBILIS.BODEGA
   DROP CONSTRAINT FK_BODEGA_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.CASA
   DROP CONSTRAINT FK_CASA_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.CLIENTE
   DROP CONSTRAINT FK_CLIENTE_REFERENCE_CONVENIO;

ALTER TABLE IMMOBILIS.CLIENTE
   DROP CONSTRAINT FK_CLIENTE_REFERENCE_PERSONA;

ALTER TABLE IMMOBILIS.COMUNA
   DROP CONSTRAINT FK_COMUNA_REFERENCE_REGION;

ALTER TABLE IMMOBILIS.CONTRATO
   DROP CONSTRAINT FK_CONTRATO_REFERENCE_CLIENTE;

ALTER TABLE IMMOBILIS.CONTRATO
   DROP CONSTRAINT FK_CONTRATO_REFERENCE_EMPLEADO;

ALTER TABLE IMMOBILIS.CONTRATO
   DROP CONSTRAINT FK_CONTRATO_REFERENCE_RESERVAP;

ALTER TABLE IMMOBILIS.CONTRATO
   DROP CONSTRAINT FK_CONTRATO_REFERENCE_SERVICIO;

ALTER TABLE IMMOBILIS.CONTRATO
   DROP CONSTRAINT FK_CONTRATO_REFERENCE_SEGURO;

ALTER TABLE IMMOBILIS.DEPARTAMENTO
   DROP CONSTRAINT FK_DEPARTAM_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.DOCUMENTO_CONTRATO
   DROP CONSTRAINT FK_DOCUMENT_REFERENCE_CONTRAT2;

ALTER TABLE IMMOBILIS.DOCUMENTO_RESPALDO
   DROP CONSTRAINT FK_DOCUMENT_REFERENCE_CONTRATO;

ALTER TABLE IMMOBILIS.EMPLEADO
   DROP CONSTRAINT FK_EMPLEADO_REFERENCE_PERSONA;

ALTER TABLE IMMOBILIS.ESTACIONAMIENTO
   DROP CONSTRAINT FK_ESTACION_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.OFICINA
   DROP CONSTRAINT FK_OFICINA_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.PAGO
   DROP CONSTRAINT FK_PAGO_REFERENCE_CONTRATO;

ALTER TABLE IMMOBILIS.PAGO
   DROP CONSTRAINT FK_PAGO_REFERENCE_CONVERSI;

ALTER TABLE IMMOBILIS.PERSONA
   DROP CONSTRAINT FK_PERSONA_REFERENCE_COMUNA;

ALTER TABLE IMMOBILIS.PROPIEDAD
   DROP CONSTRAINT FK_PROPIEDA_REFERENCE_COMUNA;

ALTER TABLE IMMOBILIS.PROPIEDAD
   DROP CONSTRAINT FK_PROPIEDA_REFERENCE_CONSTRUC;

ALTER TABLE IMMOBILIS.PROPIEDAD
   DROP CONSTRAINT FK_PROPIEDA_REFERENCE_PROPIETA;

ALTER TABLE PROPIETARIO
   DROP CONSTRAINT FK_PROPIETA_REFERENCE_PERSONA;

ALTER TABLE IMMOBILIS.REGISTROUSUARIO
   DROP CONSTRAINT FK_REGISTRO_REFERENCE_PERSONA;

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   DROP CONSTRAINT FK_RESERVAP_REFERENCE_PROPIEDA;

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   DROP CONSTRAINT FK_RESERVAP_REFERENCE_TIPORESE;

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   DROP CONSTRAINT FK_RESERVAP_REFERENCE_SEGURO;

DROP TABLE IMMOBILIS.BODEGA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.CASA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.CLIENTE CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.COMUNA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.CONSTRUCTORA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.CONTRATO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.CONVENIO CASCADE CONSTRAINTS;

DROP TABLE CONVERSION CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.DEPARTAMENTO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.DOCUMENTO_CONTRATO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.DOCUMENTO_RESPALDO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.EMPLEADO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.ESTACIONAMIENTO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.OFICINA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.PAGO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.PERSONA CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.PROPIEDAD CASCADE CONSTRAINTS;

DROP TABLE PROPIETARIO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.REGION CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.REGISTROUSUARIO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.RESERVAPROPIEDAD CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.SEGURO CASCADE CONSTRAINTS;

DROP TABLE SERVICIO CASCADE CONSTRAINTS;

DROP TABLE IMMOBILIS.TIPORESERVA CASCADE CONSTRAINTS;

DROP USER IMMOBILIS;

/*==============================================================*/
/* User: IMMOBILIS                                              */
/*==============================================================*/
CREATE USER IMMOBILIS 
  identified by "";

/*==============================================================*/
/* Table: BODEGA                                                */
/*==============================================================*/
CREATE TABLE IMMOBILIS.BODEGA 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   ALTURA               NUMBER(2,1),
   CONSTRAINT PK_BODEGA PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CASA                                                  */
/*==============================================================*/
CREATE TABLE IMMOBILIS.CASA 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   BANO                 NUMBER(1,0),
   DORMITORIO           NUMBER(1,0),
   CONJUNTO             VARCHAR2(20 BYTE),
   METROSCUADRADOSHABITABLES NUMBER(3,0),
   CONSTRAINT PK_CASA PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CLIENTE                                               */
/*==============================================================*/
CREATE TABLE IMMOBILIS.CLIENTE 
(
   RUT                  VARCHAR2(10 BYTE)    NOT NULL,
   CONVENIO             VARCHAR2(4 BYTE),
   CONSTRAINT PK_CLIENTE PRIMARY KEY (RUT)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: COMUNA                                                */
/*==============================================================*/
CREATE TABLE IMMOBILIS.COMUNA 
(
   ID_COMUNA            NUMBER(5,0)          NOT NULL,
   NOMBRE_COMUNA        VARCHAR2(50 BYTE),
   ID_REGION            NUMBER(2,0),
   CONSTRAINT PK_COMUNA PRIMARY KEY (ID_COMUNA)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CONSTRUCTORA                                          */
/*==============================================================*/
CREATE TABLE IMMOBILIS.CONSTRUCTORA 
(
   ID_CONSTRUCTORA      NUMBER(6,0)          NOT NULL,
   NOMBRE               VARCHAR2(50 BYTE),
   CONSTRAINT PK_CONSTRUCTORA PRIMARY KEY (ID_CONSTRUCTORA)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CONTRATO                                              */
/*==============================================================*/
CREATE TABLE IMMOBILIS.CONTRATO 
(
   ID_CONTRATO          NUMBER(6,0)          NOT NULL,
   ID_RESERVA           NUMBER(6,0),
   DESCUENTO            NUMBER(3,1),
   RUT                  VARCHAR2(12 BYTE),
   EMP_RUT              VARCHAR2(12 BYTE),
   ID_SERVICIO          NUMBER(6),
   ID_SEGURO            NUMBER(5,0),
   FECHA_CONTRATO       DATE,
   CONSTRAINT PK_CONTRATO PRIMARY KEY (ID_CONTRATO)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CONVENIO                                              */
/*==============================================================*/
CREATE TABLE IMMOBILIS.CONVENIO 
(
   ID                   VARCHAR2(4 BYTE)     NOT NULL,
   NOMBRE               VARCHAR2(10 BYTE),
   DESCRIPCION          VARCHAR2(40 BYTE),
   DESCUENTO            NUMBER(3,2),
   FECHA_VIGENCIA       DATE,
   CONSTRAINT PK_CONVENIO PRIMARY KEY (ID)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: CONVERSION                                            */
/*==============================================================*/
CREATE TABLE CONVERSION 
(
   ID_CONVERSION        NUMBER(10)           NOT NULL,
   FECHA_CONVERSION     DATE                 NOT NULL,
   MONEDA_ORIGEN        CHAR(3)              NOT NULL,
   MONEDA_DESTINO       CHAR(3)              NOT NULL,
   CONVERSION           NUMBER(8,2),
   CONSTRAINT PK_CONVERSION PRIMARY KEY (ID_CONVERSION)
);

/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
CREATE TABLE IMMOBILIS.DEPARTAMENTO 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   EDIFICIO             VARCHAR2(20 BYTE),
   BANO                 NUMBER(2,0),
   DORMITORIO           NUMBER(2,0),
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: DOCUMENTO_CONTRATO                                    */
/*==============================================================*/
CREATE TABLE IMMOBILIS.DOCUMENTO_CONTRATO 
(
   ID_CONTRATO          NUMBER(6,0)          NOT NULL,
   URL_BANCO            VARCHAR2(100 BYTE),
   URL_CONSERVADOR_BIENES_RAICES VARCHAR2(100 BYTE),
   URL_NOTARIA          VARCHAR2(100 BYTE),
   URL_TASACION         VARCHAR2(100 BYTE),
   CONSTRAINT PK_DOCUMENTO_CONTRATO PRIMARY KEY (ID_CONTRATO)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: DOCUMENTO_RESPALDO                                    */
/*==============================================================*/
CREATE TABLE IMMOBILIS.DOCUMENTO_RESPALDO 
(
   ID_CONTRATO          NUMBER(6,0)          NOT NULL,
   URL_AVAL             VARCHAR2(100 BYTE),
   URL_BOLETA_HONORARIO VARCHAR2(100 BYTE),
   URL_CONTRATO_TRABAJO VARCHAR2(100 BYTE),
   URL_FOTOCOPIA_CEDULA_IDENTIDAD VARCHAR2(100 BYTE),
   URL_LIQUIDACION_SUELDO VARCHAR2(100 BYTE),
   CONSTRAINT PK_DOCUMENTO_RESPALDO PRIMARY KEY (ID_CONTRATO)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: EMPLEADO                                              */
/*==============================================================*/
CREATE TABLE IMMOBILIS.EMPLEADO 
(
   RUT                  VARCHAR2(12 BYTE)    NOT NULL,
   CARGO                VARCHAR2(12 BYTE),
   CONSTRAINT PK_EMPLEADO PRIMARY KEY (RUT)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: ESTACIONAMIENTO                                       */
/*==============================================================*/
CREATE TABLE IMMOBILIS.ESTACIONAMIENTO 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   NIVEL                NUMBER(2,0),
   CONSTRAINT PK_ESTACIONAMIENTO PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: OFICINA                                               */
/*==============================================================*/
CREATE TABLE IMMOBILIS.OFICINA 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   PATENTECOMERCIAL     NUMBER(10,0),
   CONSTRAINT PK_OFICINA PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: PAGO                                                  */
/*==============================================================*/
CREATE TABLE IMMOBILIS.PAGO 
(
   ESTADO_PAGO          VARCHAR2(8 BYTE),
   FECHA_VENCIMIENTO    DATE,
   ID_VENCIMIENTO       NUMBER(5,0)          NOT NULL,
   ID_CONTRATO          NUMBER(5,0),
   ID_CONVERSION        NUMBER(10),
   MONTO_CUOTA          NUMBER(10,2),
   N_CUOTA              NUMBER(2,0),
   COMISION             NUMBER(3,2),
   FECHA_PAGADA         DATE,
   CONSTRAINT PK_PAGO PRIMARY KEY (ID_VENCIMIENTO)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: PERSONA                                               */
/*==============================================================*/
CREATE TABLE IMMOBILIS.PERSONA 
(
   RUT                  VARCHAR2(10 BYTE)    NOT NULL,
   ID_COMUNA            NUMBER(5,0),
   NOMBRE               VARCHAR2(30 BYTE),
   PATERNO              VARCHAR2(15 BYTE),
   MATERNO              VARCHAR2(15 BYTE),
   SEXO                 CHAR(1 BYTE),
   DIRECCION            VARCHAR2(30 BYTE),
   FECHA_NACIMIENTO     DATE,
   MAIL                 VARCHAR2(50 BYTE),
   FECHA_INGRESO        DATE,
   TELEFONO             VARCHAR2(12 BYTE),
   CONSTRAINT PK_PERSONA PRIMARY KEY (RUT)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: PROPIEDAD                                             */
/*==============================================================*/
CREATE TABLE IMMOBILIS.PROPIEDAD 
(
   ID_PROPIEDAD         NUMBER(5,0)          NOT NULL,
   ID_COMUNA            NUMBER(5,0),
   ID_CONSTRUCTORA      NUMBER(6,0),
   TIPO_PROPIEDAD       VARCHAR2(20 BYTE),
   DESCRIPCION          VARCHAR2(400 BYTE),
   OPERACION            VARCHAR2(10 BYTE),
   DISPONIBLE           CHAR(1 BYTE),
   PROYECTO             VARCHAR2(20 BYTE),
   METROS_CUADRADOS     NUMBER(5,0),
   PRECIO_UF            NUMBER(6,0),
   DIRECCION            VARCHAR2(50),
   RUT_PROPIETARIO      VARCHAR2(10),
   CONSTRAINT PK_PROPIEDAD PRIMARY KEY (ID_PROPIEDAD)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: PROPIETARIO                                           */
/*==============================================================*/
CREATE TABLE PROPIETARIO 
(
   RUT                  VARCHAR2(10 BYTE)    NOT NULL,
   DIA_PAGO             NUMBER(2),
   FORMA_PAGO           VARCHAR(10),
   CONSTRAINT PK_PROPIETARIO PRIMARY KEY (RUT)
);

/*==============================================================*/
/* Table: REGION                                                */
/*==============================================================*/
CREATE TABLE IMMOBILIS.REGION 
(
   ID_REGION            NUMBER(2,0)          NOT NULL,
   NOMBRE_REGION        VARCHAR2(100 BYTE),
   CONSTRAINT PK_REGION PRIMARY KEY (ID_REGION)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: REGISTROUSUARIO                                       */
/*==============================================================*/
CREATE TABLE IMMOBILIS.REGISTROUSUARIO 
(
   RUT                  VARCHAR2(12 BYTE)    NOT NULL,
   ACTIVO               NUMBER(1,0),
   PASSWORD             VARCHAR2(7 BYTE),
   CONSTRAINT REGISTROUSUARIO PRIMARY KEY (RUT)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: RESERVAPROPIEDAD                                      */
/*==============================================================*/
CREATE TABLE IMMOBILIS.RESERVAPROPIEDAD 
(
   ID_RESERVA           NUMBER(5,0)          NOT NULL,
   ID_PROPIEDAD         NUMBER(5,0),
   ID_TIPO_RESERVA      NUMBER(1,0),
   ID_SEGURO            NUMBER(5,0),
   FECHA                DATE,
   RUT                  VARCHAR2(10 BYTE),
   CONSTRAINT PK_RESERVAPROPIEDAD PRIMARY KEY (ID_RESERVA)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: SEGURO                                                */
/*==============================================================*/
CREATE TABLE IMMOBILIS.SEGURO 
(
   ID_SEGURO            NUMBER(5,0)          NOT NULL,
   COMPANIA             VARCHAR2(20 BYTE),
   MONTO                NUMBER(6,0),
   GLOSA                VARCHAR2(400 BYTE),
   CONSTRAINT PK_SEGURO PRIMARY KEY (ID_SEGURO)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

/*==============================================================*/
/* Table: SERVICIO                                              */
/*==============================================================*/
CREATE TABLE SERVICIO 
(
   ID_SERVICIO          NUMBER(6)            NOT NULL,
   DESCRIPCION          VARCHAR2(20),
   FECHAVIGENCIA        DATE,
   VALOR                DATE,
   CONSTRAINT PK_SERVICIO PRIMARY KEY (ID_SERVICIO)
);

/*==============================================================*/
/* Table: TIPORESERVA                                           */
/*==============================================================*/
CREATE TABLE IMMOBILIS.TIPORESERVA 
(
   ID_TIPO_RESERVA      NUMBER(1,0)          NOT NULL,
   DESCRIPCION          VARCHAR2(10 BYTE),
   CONSTRAINT PK_TIPORESERVA PRIMARY KEY (ID_TIPO_RESERVA)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE
)
SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

ALTER TABLE IMMOBILIS.BODEGA
   ADD CONSTRAINT FK_BODEGA_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.CASA
   ADD CONSTRAINT FK_CASA_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.CLIENTE
   ADD CONSTRAINT FK_CLIENTE_REFERENCE_CONVENIO FOREIGN KEY (CONVENIO)
      REFERENCES IMMOBILIS.CONVENIO (ID);

ALTER TABLE IMMOBILIS.CLIENTE
   ADD CONSTRAINT FK_CLIENTE_REFERENCE_PERSONA FOREIGN KEY (RUT)
      REFERENCES IMMOBILIS.PERSONA (RUT);

ALTER TABLE IMMOBILIS.COMUNA
   ADD CONSTRAINT FK_COMUNA_REFERENCE_REGION FOREIGN KEY (ID_REGION)
      REFERENCES IMMOBILIS.REGION (ID_REGION);

ALTER TABLE IMMOBILIS.CONTRATO
   ADD CONSTRAINT FK_CONTRATO_REFERENCE_CLIENTE FOREIGN KEY (RUT)
      REFERENCES IMMOBILIS.CLIENTE (RUT);

ALTER TABLE IMMOBILIS.CONTRATO
   ADD CONSTRAINT FK_CONTRATO_REFERENCE_EMPLEADO FOREIGN KEY (EMP_RUT)
      REFERENCES IMMOBILIS.EMPLEADO (RUT);

ALTER TABLE IMMOBILIS.CONTRATO
   ADD CONSTRAINT FK_CONTRATO_REFERENCE_RESERVAP FOREIGN KEY (ID_RESERVA)
      REFERENCES IMMOBILIS.RESERVAPROPIEDAD (ID_RESERVA);

ALTER TABLE IMMOBILIS.CONTRATO
   ADD CONSTRAINT FK_CONTRATO_REFERENCE_SERVICIO FOREIGN KEY (ID_SERVICIO)
      REFERENCES SERVICIO (ID_SERVICIO);

ALTER TABLE IMMOBILIS.CONTRATO
   ADD CONSTRAINT FK_CONTRATO_REFERENCE_SEGURO FOREIGN KEY (ID_SEGURO)
      REFERENCES IMMOBILIS.SEGURO (ID_SEGURO);

ALTER TABLE IMMOBILIS.DEPARTAMENTO
   ADD CONSTRAINT FK_DEPARTAM_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.DOCUMENTO_CONTRATO
   ADD CONSTRAINT FK_DOCUMENT_REFERENCE_CONTRAT2 FOREIGN KEY (ID_CONTRATO)
      REFERENCES IMMOBILIS.CONTRATO (ID_CONTRATO);

ALTER TABLE IMMOBILIS.DOCUMENTO_RESPALDO
   ADD CONSTRAINT FK_DOCUMENT_REFERENCE_CONTRATO FOREIGN KEY (ID_CONTRATO)
      REFERENCES IMMOBILIS.CONTRATO (ID_CONTRATO);

ALTER TABLE IMMOBILIS.EMPLEADO
   ADD CONSTRAINT FK_EMPLEADO_REFERENCE_PERSONA FOREIGN KEY (RUT)
      REFERENCES IMMOBILIS.PERSONA (RUT);

ALTER TABLE IMMOBILIS.ESTACIONAMIENTO
   ADD CONSTRAINT FK_ESTACION_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.OFICINA
   ADD CONSTRAINT FK_OFICINA_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.PAGO
   ADD CONSTRAINT FK_PAGO_REFERENCE_CONTRATO FOREIGN KEY (ID_CONTRATO)
      REFERENCES IMMOBILIS.CONTRATO (ID_CONTRATO);

ALTER TABLE IMMOBILIS.PAGO
   ADD CONSTRAINT FK_PAGO_REFERENCE_CONVERSI FOREIGN KEY (ID_CONVERSION)
      REFERENCES CONVERSION (ID_CONVERSION);

ALTER TABLE IMMOBILIS.PERSONA
   ADD CONSTRAINT FK_PERSONA_REFERENCE_COMUNA FOREIGN KEY (ID_COMUNA)
      REFERENCES IMMOBILIS.COMUNA (ID_COMUNA);

ALTER TABLE IMMOBILIS.PROPIEDAD
   ADD CONSTRAINT FK_PROPIEDA_REFERENCE_COMUNA FOREIGN KEY (ID_COMUNA)
      REFERENCES IMMOBILIS.COMUNA (ID_COMUNA);

ALTER TABLE IMMOBILIS.PROPIEDAD
   ADD CONSTRAINT FK_PROPIEDA_REFERENCE_CONSTRUC FOREIGN KEY (ID_CONSTRUCTORA)
      REFERENCES IMMOBILIS.CONSTRUCTORA (ID_CONSTRUCTORA);

ALTER TABLE IMMOBILIS.PROPIEDAD
   ADD CONSTRAINT FK_PROPIEDA_REFERENCE_PROPIETA FOREIGN KEY (RUT_PROPIETARIO)
      REFERENCES PROPIETARIO (RUT);

ALTER TABLE PROPIETARIO
   ADD CONSTRAINT FK_PROPIETA_REFERENCE_PERSONA FOREIGN KEY (RUT)
      REFERENCES IMMOBILIS.PERSONA (RUT);

ALTER TABLE IMMOBILIS.REGISTROUSUARIO
   ADD CONSTRAINT FK_REGISTRO_REFERENCE_PERSONA FOREIGN KEY (RUT)
      REFERENCES IMMOBILIS.PERSONA (RUT);

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   ADD CONSTRAINT FK_RESERVAP_REFERENCE_PROPIEDA FOREIGN KEY (ID_PROPIEDAD)
      REFERENCES IMMOBILIS.PROPIEDAD (ID_PROPIEDAD);

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   ADD CONSTRAINT FK_RESERVAP_REFERENCE_TIPORESE FOREIGN KEY (ID_TIPO_RESERVA)
      REFERENCES IMMOBILIS.TIPORESERVA (ID_TIPO_RESERVA);

ALTER TABLE IMMOBILIS.RESERVAPROPIEDAD
   ADD CONSTRAINT FK_RESERVAP_REFERENCE_SEGURO FOREIGN KEY (ID_SEGURO)
      REFERENCES IMMOBILIS.SEGURO (ID_SEGURO);

