DELETE FROM REGION;
insert into region (id_Region, nombre_region) values (01,'De Tarapacá');
insert into region (id_Region, nombre_region) values (02,'De Antofagasta');
insert into region (id_Region, nombre_region) values (03,'De Atacama');
insert into region (id_Region, nombre_region) values (04,'De Coquimbo');
insert into region (id_Region, nombre_region) values (05,'De Valparaíso');
insert into region (id_Region, nombre_region) values (06,'Del Libertador B. OHiggins');
insert into region (id_Region, nombre_region) values (07,'Del Maule');
insert into region (id_Region, nombre_region) values (08,'Del Bíobío');
insert into region (id_Region, nombre_region) values (09,'De La Araucanía');
insert into region (id_Region, nombre_region) values (14,'De Los Ríos');
insert into region (id_Region, nombre_region) values (10,'De Los Lagos');
insert into region (id_Region, nombre_region) values (11,'De Aisén del Gral. C. Ibáñez del Campo');
insert into region (id_Region, nombre_region) values (12,'De Magallanes y de La Antártica Chilena');
insert into region (id_Region, nombre_region) values (13,'Metropolitana de Santiago');
insert into region (id_Region, nombre_region) values (99,'Ignorada');
COMMIT;
DELETE FROM COMUNA;
insert into comuna (id_Comuna,nombre_comuna,id_region) values (15101,'Arica',15);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (15102,'Camarones',15);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (15201,'Putre',15);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (15202,'General Lagos',15);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1101,'Iquique',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1402,'Camiña',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1403,'Colchane',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1404,'Huara',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1405,'Pica',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1401,'Pozo Almonte',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (1107,'Alto Hospicio',01);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2101,'Antofagasta',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2102,'Mejillones',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2103,'Sierra Gorda',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2104,'Taltal',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2201,'Calama',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2202,'Ollagüe',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2203,'San Pedro de Atacama',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2301,'Tocopilla',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (2302,'María Elena',02);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3101,'Copiapó',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3102,'Caldera',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3103,'Tierra Amarilla',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3201,'Chañaral',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3202,'Diego de Almagro',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3301,'Vallenar',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3302,'Alto del Carmen',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3303,'Freirina',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (3304,'Huasco',03);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4101,'La Serena',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4102,'Coquimbo',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4103,'Andacollo',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4104,'La Higuera',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4105,'Paiguano',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4106,'Vicuña',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4201,'Illapel',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4202,'Canela',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4203,'Los Vilos',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4204,'Salamanca',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4301,'Ovalle',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4302,'Combarbalá',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4303,'Monte Patria',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4304,'Punitaqui',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (4305,'Río Hurtado',04);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5101,'Valparaíso',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5102,'Casablanca',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5103,'Concón',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5104,'Juan Fernández',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5105,'Puchuncaví',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5801,'Quilpué',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5107,'Quintero',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5804,'Villa Alemana',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5109,'Viña del Mar',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5201,'Isla  de Pascua',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5301,'Los Andes',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5302,'Calle Larga',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5303,'Rinconada',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5304,'San Esteban',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5401,'La Ligua',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5402,'Cabildo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5403,'Papudo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5404,'Petorca',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5405,'Zapallar',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5501,'Quillota',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5502,'Calera',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5503,'Hijuelas',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5504,'La Cruz',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5802,'Limache',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5506,'Nogales',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5803,'Olmué',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5601,'San Antonio',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5602,'Algarrobo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5603,'Cartagena',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5604,'El Quisco',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5605,'El Tabo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5606,'Santo Domingo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5701,'San Felipe',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5702,'Catemu',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5703,'Llaillay',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5704,'Panquehue',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5705,'Putaendo',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (5706,'Santa María',05);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6101,'Rancagua',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6102,'Codegua',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6103,'Coinco',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6104,'Coltauco',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6105,'Doñihue',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6106,'Graneros',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6107,'Las Cabras',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6108,'Machalí',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6109,'Malloa',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6110,'Mostazal',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6111,'Olivar',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6112,'Peumo',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6113,'Pichidegua',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6114,'Quinta de Tilcoco',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6115,'Rengo',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6116,'Requínoa',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6117,'San Vicente',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6201,'Pichilemu',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6202,'La Estrella',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6203,'Litueche',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6204,'Marchihue',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6205,'Navidad',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6206,'Paredones',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6301,'San Fernando',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6302,'Chépica',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6303,'Chimbarongo',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6304,'Lolol',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6305,'Nancagua',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6306,'Palmilla',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6307,'Peralillo',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6308,'Placilla',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6309,'Pumanque',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (6310,'Santa Cruz',06);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7101,'Talca',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7102,'Constitución',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7103,'Curepto',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7104,'Empedrado',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7105,'Maule',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7106,'Pelarco',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7107,'Pencahue',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7108,'Río Claro',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7109,'San Clemente',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7110,'San Rafael',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7201,'Cauquenes',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7202,'Chanco',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7203,'Pelluhue',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7301,'Curicó',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7302,'Hualañé',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7303,'Licantén',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7304,'Molina',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7305,'Rauco',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7306,'Romeral',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7307,'Sagrada Familia',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7308,'Teno',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7309,'Vichuquén',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7401,'Linares',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7402,'Colbún',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7403,'Longaví',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7404,'Parral',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7405,'Retiro',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7406,'San Javier',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7407,'Villa Alegre',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (7408,'Yerbas Buenas',07);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8101,'Concepción',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8102,'Coronel',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8103,'Chiguayante',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8104,'Florida',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8105,'Hualqui',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8106,'Lota',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8107,'Penco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8108,'San Pedro de la Paz',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8109,'Santa Juana',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8110,'Talcahuano',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8111,'Tomé',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8112,'Hualpén',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8201,'Lebu',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8202,'Arauco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8203,'Cañete',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8204,'Contulmo',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8205,'Curanilahue',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8206,'Los Álamos',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8207,'Tirúa',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8301,'Los Ángeles',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8302,'Antuco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8303,'Cabrero',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8304,'Laja',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8305,'Mulchén',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8306,'Nacimiento',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8307,'Negrete',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8308,'Quilaco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8309,'Quilleco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8310,'San Rosendo',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8311,'Santa Bárbara',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8312,'Tucapel',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8313,'Yumbel',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8314,'Alto Biobío',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8401,'Chillán',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8402,'Bulnes',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8403,'Cobquecura',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8404,'Coelemu',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8405,'Coihueco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8406,'Chillán Viejo',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8407,'El Carmen',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8408,'Ninhue',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8409,'Ñiquén',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8410,'Pemuco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8411,'Pinto',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8412,'Portezuelo',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8413,'Quillón',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8414,'Quirihue',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8415,'Ránquil',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8416,'San Carlos',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8417,'San Fabián',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8418,'San Ignacio',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8419,'San Nicolás',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8420,'Treguaco',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (8421,'Yungay',08);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9101,'Temuco',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9102,'Carahue',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9103,'Cunco',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9104,'Curarrehue',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9105,'Freire',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9106,'Galvarino',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9107,'Gorbea',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9108,'Lautaro',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9109,'Loncoche',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9110,'Melipeuco',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9111,'Nueva Imperial',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9112,'Padre Las Casas',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9113,'Perquenco',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9114,'Pitrufquén',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9115,'Pucón',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9116,'Saavedra',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9117,'Teodoro Schmidt',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9118,'Toltén',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9119,'Vilcún',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9120,'Villarrica',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9121,'Cholchol',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9201,'Angol',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9202,'Collipulli',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9203,'Curacautín',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9204,'Ercilla',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9205,'Lonquimay',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9206,'Los Sauces',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9207,'Lumaco',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9208,'Purén',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9209,'Renaico',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9210,'Traiguén',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (9211,'Victoria',09);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14101,'Valdivia',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14102,'Corral',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14202,'Futrono',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14201,'La Unión',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14203,'Lago Ranco',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14103,'Lanco',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14104,'Los Lagos',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14105,'Máfil',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14106,'Mariquina',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14107,'Paillaco',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14108,'Panguipulli',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (14204,'Río Bueno',14);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10101,'Puerto Montt',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10102,'Calbuco',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10103,'Cochamó',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10104,'Fresia',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10105,'Frutillar',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10106,'Los Muermos',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10107,'Llanquihue',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10108,'Maullín',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10109,'Puerto Varas',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10201,'Castro',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10202,'Ancud',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10203,'Chonchi',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10204,'Curaco de Vélez',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10205,'Dalcahue',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10206,'Puqueldón',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10207,'Queilén',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10208,'Quellón',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10209,'Quemchi',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10210,'Quinchao',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10301,'Osorno',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10302,'Puerto Octay',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10303,'Purranque',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10304,'Puyehue',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10305,'Río Negro',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10306,'San Juan de la Costa',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10307,'San Pablo',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10401,'Chaitén',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10402,'Futaleufú',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10403,'Hualaihué',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (10404,'Palena',10);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11101,'Coihaique',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11102,'Lago Verde',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11201,'Aisén',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11202,'Cisnes',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11203,'Guaitecas',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11301,'Cochrane',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11302,'OHiggins',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11303,'Tortel',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11401,'Chile Chico',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (11402,'Río Ibáñez',11);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12101,'Punta Arenas',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12102,'Laguna Blanca',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12103,'Río Verde',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12104,'San Gregorio',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12201,'Cabo de Hornos',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12202,'Antártica',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12301,'Porvenir',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12302,'Primavera',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12303,'Timaukel',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12401,'Natales',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (12402,'Torres del Paine',12);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13101,'Santiago',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13102,'Cerrillos',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13103,'Cerro Navia',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13104,'Conchalí',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13105,'El Bosque',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13106,'Estación Central',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13107,'Huechuraba',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13108,'Independencia',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13109,'La Cisterna',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13110,'La Florida',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13111,'La Granja',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13112,'La Pintana',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13113,'La Reina',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13114,'Las Condes',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13115,'Lo Barnechea',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13116,'Lo Espejo',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13117,'Lo Prado',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13118,'Macul',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13119,'Maipú',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13120,'Ñuñoa',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13121,'Pedro Aguirre Cerda',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13122,'Peñalolén',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13123,'Providencia',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13124,'Pudahuel',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13125,'Quilicura',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13126,'Quinta Normal',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13127,'Recoleta',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13128,'Renca',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13129,'San Joaquín',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13130,'San Miguel',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13131,'San Ramón',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13132,'Vitacura',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13201,'Puente Alto',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13202,'Pirque',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13203,'San José de Maipo',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13301,'Colina',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13302,'Lampa',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13303,'Tiltil',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13401,'San Bernardo',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13402,'Buin',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13403,'Calera de Tango',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13404,'Paine',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13501,'Melipilla',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13502,'Alhué',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13503,'Curacaví',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13504,'María Pinto',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13505,'San Pedro',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13601,'Talagante',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13602,'El Monte',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13603,'Isla de Maipo',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13604,'Padre Hurtado',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (13605,'Peñaflor',13);
insert into comuna (id_Comuna,nombre_comuna,id_region) values (99999,'Ignorada',99);
COMMIT;