--------------------------------------------------------
	-- Archivo creado  - miércoles-octubre-28-2015   
	--------------------------------------------------------
	--------------------------------------------------------
	--  DDL for Package PKG_PROPIEDADES
--------------------------------------------------------

CREATE OR REPLACE PACKAGE "IMMOBILIS"."PKG_PROPIEDADES" AS				

TYPE RefCursor is REF CURSOR;

procedure FILTER_PROPIEDADES (
	COD_RESULTADO	OUT	NUMBER	,	
	MSG_ERROR	OUT	varchar2	,	
	CURSOR_PROPIEDAD	OUT	PKG_PROPIEDADES.REFCURSOR	,
	SP_TIPO_OPERACION IN VARCHAR2,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
    SP_UBICACION IN VARCHAR2
);

-- BUSCAR x ID_PROPIEDAD

procedure SP_BUSCAR_ID_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT VARCHAR2,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER
	
);


procedure SP_INGRESA_NUEVA_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT varchar2,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER,
	SP_ALTURA IN NUMBER,
	SP_BANO IN NUMBER,
	SP_DORMITORIO IN NUMBER,
	SP_CONJUNTO IN VARCHAR2,
	SP_METROSCUADRADOSHABILES IN NUMBER,
	SP_EDIFICIO IN VARCHAR2,
	SP_PATENTECOMERCIAL NUMBER,
	SP_NIVEL IN NUMBER,
	SP_ID_COMUNA IN NUMBER,
	SP_NOMBRE_COMUNA IN VARCHAR2,
    SP_ID_REGION IN NUMBER,
	SP_ID_CONSTRUCTORA IN NUMBER,
	SP_NOMBRE IN VARCHAR2,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
	SP_DESCRIPCION IN VARCHAR2,
	SP_OPERACION IN VARCHAR2,
	SP_DISPONIBLE IN CHAR,
	SP_PROYECTO IN VARCHAR2,
	SP_METROS_CUADRADOS IN NUMBER,
	SP_PRECIO_UF IN NUMBER,
	SP_DIRECCION IN VARCHAR2,
	SP_RUT_PROPIETARIO IN VARCHAR2
);	

procedure SP_ACTUALIZA_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT VARCHAR,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER,
	SP_ID_COMUNA IN NUMBER,
	SP_ID_CONSTRUCTORA IN NUMBER,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
	SP_DESCRIPCION IN VARCHAR2,
	SP_OPERACION IN VARCHAR2,
	SP_DISPONIBLE IN CHAR,
	SP_PROYECTO IN VARCHAR2,
	SP_METROS_CUADRADOS IN NUMBER,
	SP_PRECIO_UF IN NUMBER,
	SP_DIRECCION IN VARCHAR2,
	SP_RUT_PROPIETARIO IN VARCHAR2
);							   

END "PKG_PROPIEDADES";

/
