--------------------------------------------------------
	-- Archivo creado  - miércoles-octubre-28-2015   
	--------------------------------------------------------
	--------------------------------------------------------
	--  DDL for Package Body PKG_PROPIEDADES
--------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY "IMMOBILIS"."PKG_PROPIEDADES" 		AS				


procedure FILTER_PROPIEDADES (
	COD_RESULTADO	OUT	NUMBER	,	
	MSG_ERROR	OUT	varchar2	,	
	CURSOR_PROPIEDAD	OUT	PKG_PROPIEDADES.REFCURSOR	,
	SP_TIPO_OPERACION IN VARCHAR2,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
SP_UBICACION IN VARCHAR2)
AS 

BEGIN
	
	
	COD_RESULTADO:=1;
	
	OPEN CURSOR_PROPIEDAD FOR
	
	
	SELECT ID_PROPIEDAD,
	PRO.ID_COMUNA,
	PRO.ID_INMOBILIARIA,
	PRO.TIPO_PROPIEDAD,
	PRO.DESCRIPCION,
	PRO.PRECIO,
	PRO.OPERACION,
	PRO.DISPONIBLE,
	CO.NOMBRE_COMUNA,
	RE.NOMBRE_REGION
	
	FROM 
	PROPIEDAD PRO
	JOIN 
	COMUNA CO ON CO.ID_COMUNA = PRO.ID_COMUNA
	JOIN 
	REGION RE ON RE.ID_REGION=CO.ID_REGION
	JOIN 
	INMOBILIARIA IMM ON PRO.ID_INMOBILIARIA = IMM.ID_INMOBILIARIA
	WHERE
	PRO.TIPO_PROPIEDAD LIKE NVL(SP_TIPO_PROPIEDAD,'%')
	AND
	PRO.OPERACION LIKE NVL(SP_TIPO_OPERACION,'%')
	
	AND (CO.NOMBRE_COMUNA LIKE NVL(SP_UBICACION,'%') OR RE.NOMBRE_REGION LIKE NVL(SP_UBICACION,'%') )
	
	AND PRO.DISPONIBLE = 'Y';
	
	COD_RESULTADO:=0;
	
	EXCEPTION 
	WHEN OTHERS THEN
	
	MSG_ERROR:= 'ERROR AL FILTRAR';
END;

--     SP_INGRESA_NUEVA_PROPIEDAD   --
procedure SP_INGRESA_NUEVA_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT varchar2,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER,
	SP_ALTURA IN NUMBER,
	SP_BANO IN NUMBER,
	SP_DORMITORIO IN NUMBER,
	SP_CONJUNTO IN VARCHAR2,
	SP_METROSCUADRADOSHABILES IN NUMBER,
	SP_EDIFICIO IN VARCHAR2,
	SP_PATENTECOMERCIAL NUMBER,
	SP_NIVEL IN NUMBER,
	SP_ID_COMUNA IN NUMBER,
	SP_NOMBRE_COMUNA IN VARCHAR2,
    SP_ID_REGION IN NUMBER,
	SP_ID_CONSTRUCTORA IN NUMBER,
	SP_NOMBRE IN VARCHAR2,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
	SP_DESCRIPCION IN VARCHAR2,
	SP_OPERACION IN VARCHAR2,
	SP_DISPONIBLE IN CHAR,
	SP_PROYECTO IN VARCHAR2,
	SP_METROS_CUADRADOS IN NUMBER,
	SP_PRECIO_UF IN NUMBER,
	SP_DIRECCION IN VARCHAR2,
    SP_RUT_PROPIETARIO IN VARCHAR2)

IS
coincidencias number(9);
BEGIN
	cod_resultado:=1;
	
	INSERT
	
	INTO PROPIEDAD
	(
		ID_PROPIEDAD,
		ID_COMUNA,
		ID_CONSTRUCTORA,
		TIPO_PROPIEDAD,
		DESCRIPCION,
		OPERACION,
		DISPONIBLE,
		PROYECTO,
		METROS_CUADRADOS,
		PRECIO_UF,
		DIRECCION,
		RUT_PROPIETARIO
	)
	VALUES
	(
		SP_ID_PROPIEDAD,
		SP_ID_COMUNA,
		SP_ID_CONSTRUCTORA,
		SP_TIPO_PROPIEDAD,
		SP_DESCRIPCION,
		SP_OPERACION,
		SP_DISPONIBLE,
		SP_PROYECTO,
		SP_METROS_CUADRADOS,
		SP_PRECIO_UF,
		SP_DIRECCION,
		SP_RUT_PROPIETARIO
	);
	cod_resultado:=2;
	
	EXCEPTION WHEN OTHERS THEN
	msg_error := 'ERROR: ' || SQLERRM || ' (' || SQLCODE  || ')';
END;

--  SP_ACTUALIZA_PROPIEDAD
procedure SP_ACTUALIZA_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT VARCHAR,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER,
	SP_ID_COMUNA IN NUMBER,
	SP_ID_CONSTRUCTORA IN NUMBER,
	SP_TIPO_PROPIEDAD IN VARCHAR2,
	SP_DESCRIPCION IN VARCHAR2,
	SP_OPERACION IN VARCHAR2,
	SP_DISPONIBLE IN CHAR,
	SP_PROYECTO IN VARCHAR2,
	SP_METROS_CUADRADOS IN NUMBER,
	SP_PRECIO_UF IN NUMBER,
	SP_DIRECCION IN VARCHAR2,
	SP_RUT_PROPIETARIO IN VARCHAR2
)
IS

coincidencias number(9);

BEGIN
	cod_resultado:= 1;
	--
	--
	select count(pro.ID_PROPIEDAD) into coincidencias from PROPIEDAD pro where pro.ID_PROPIEDAD=SP_ID_PROPIEDAD;
	IF (coincidencias = 0) then
		
		raise TOO_MANY_ROWS;
		
	end if;
	
	update 
    propiedad 
	set 	
    ID_PROPIEDAD	=	SP_ID_PROPIEDAD	,			
    ID_COMUNA	=	SP_ID_COMUNA	,			
    ID_CONSTRUCTORA	=	SP_ID_CONSTRUCTORA	,			
    TIPO_PROPIEDAD	=	SP_TIPO_PROPIEDAD	,			
    DESCRIPCION	=	SP_DESCRIPCION	,			
    OPERACION	=	SP_OPERACION	,			
    DISPONIBLE	=	SP_DISPONIBLE	,			
    PROYECTO	=	SP_PROYECTO	,			
    METROS_CUADRADOS	=	SP_METROS_CUADRADOS	,					
    PRECIO_UF	=	SP_PRECIO_UF,
	DIRECCION = SP_DIRECCION,
	RUT_PROPIETARIO = SP_RUT_PROPIETARIO
	where	
    ID_PROPIEDAD	= SP_ID_PROPIEDAD;
    
	and 
    ACTIVO=1;
	
	EXCEPTION WHEN OTHERS THEN
	msg_error := 'ERROR: ' || SQLERRM || ' (' || SQLCODE  || ')';
END;

-- BUSCAR x ID_PROPIEDAD
procedure SP_BUSCAR_ID_PROPIEDAD(
	COD_RESULTADO OUT NUMBER,
	MSG_ERROR OUT VARCHAR2,
	CURSOR_PROPIEDAD OUT PKG_PROPIEDADES.REFCURSOR,
	SP_ID_PROPIEDAD IN NUMBER
	
)
IS
BEGIN
  cod_resultado:=0;
 open cursorPropiedad for 
SELECT 
  PRO.ID_PROPIEDAD,
  PRO.ID_COMUNA,
  PRO.ID_CONSTRUCTORA,
  PRO.TIPO_PROPIEDAD,
  PRO.DESCRIPCION,
  PRO.OPERACION,
  PRO.DISPONIBLE,
  PRO.PROYECTO,
  PRO.METROS_CUADRADOS,
  PRO.PRECIO_UF,
  PRO.DIRECCION,
  PRO.RUT_PROPIETARIO
  

FROM 
  PROPIEDAD PRO
join 
  REGISTROPROPIEDAD reg on PRO.ID_PROPIEDAD = reg.ID_PROPIEDAD
where 
  reg.activo =1
AND 
  pro.ID_PROPIEDAD=SP_ID_PROPIEDAD;
  
  cod_resultado:=0;
  
 EXCEPTION WHEN OTHERS THEN
  msg_error :='Ha ocurrido un error al buscar la propiedad '||sp_rut;  
  
END;

END;

/
