--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-02-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BODEGA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."BODEGA" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"ALTURA" NUMBER(2,1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CASA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CASA" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"BANO" NUMBER(1,0), 
	"DORMITORIO" NUMBER(1,0), 
	"CONJUNTO" VARCHAR2(20 BYTE), 
	"METROSCUADRADOSHABITABLES" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CLIENTE" 
   (	"RUT" VARCHAR2(10 BYTE), 
	"CONVENIO" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."COMUNA" 
   (	"ID_COMUNA" NUMBER(5,0), 
	"NOMBRE_COMUNA" VARCHAR2(50 BYTE), 
	"ID_REGION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSTRUCTORA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CONSTRUCTORA" 
   (	"ID_CONSTRUCTORA" NUMBER(6,0), 
	"NOMBRE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTRATO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CONTRATO" 
   (	"ID_CONTRATO" NUMBER(6,0), 
	"ID_RESERVA" NUMBER(6,0), 
	"DESCUENTO" NUMBER(3,1), 
	"RUT" VARCHAR2(12 BYTE), 
	"EMP_RUT" VARCHAR2(12 BYTE), 
	"ID_SERVICIO" NUMBER(6,0), 
	"ID_SEGURO" NUMBER(5,0), 
	"FECHA_CONTRATO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONVENIO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CONVENIO" 
   (	"ID" VARCHAR2(4 BYTE), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"DESCUENTO" NUMBER(3,2), 
	"FECHA_VIGENCIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONVERSION
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."CONVERSION" 
   (	"ID_CONVERSION" NUMBER(10,0), 
	"FECHA_CONVERSION" DATE, 
	"MONEDA_ORIGEN" CHAR(3 BYTE), 
	"MONEDA_DESTINO" CHAR(3 BYTE), 
	"CONVERSION" NUMBER(8,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."DEPARTAMENTO" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"EDIFICIO" VARCHAR2(20 BYTE), 
	"BANO" NUMBER(2,0), 
	"DORMITORIO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTO_CONTRATO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."DOCUMENTO_CONTRATO" 
   (	"ID_CONTRATO" NUMBER(6,0), 
	"URL_BANCO" VARCHAR2(100 BYTE), 
	"URL_CONSERVADOR_BIENES_RAICES" VARCHAR2(100 BYTE), 
	"URL_NOTARIA" VARCHAR2(100 BYTE), 
	"URL_TASACION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTO_RESPALDO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."DOCUMENTO_RESPALDO" 
   (	"ID_CONTRATO" NUMBER(6,0), 
	"URL_AVAL" VARCHAR2(100 BYTE), 
	"URL_BOLETA_HONORARIO" VARCHAR2(100 BYTE), 
	"URL_CONTRATO_TRABAJO" VARCHAR2(100 BYTE), 
	"URL_FOTOCOPIA_CEDULA_IDENTIDAD" VARCHAR2(100 BYTE), 
	"URL_LIQUIDACION_SUELDO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."EMPLEADO" 
   (	"RUT" VARCHAR2(12 BYTE), 
	"CARGO" VARCHAR2(12 BYTE), 
	"PASSWORD" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTACIONAMIENTO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."ESTACIONAMIENTO" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"NIVEL" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFICINA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."OFICINA" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"PATENTECOMERCIAL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAGO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."PAGO" 
   (	"ESTADO_PAGO" VARCHAR2(8 BYTE), 
	"FECHA_VENCIMIENTO" DATE, 
	"ID_VENCIMIENTO" NUMBER(5,0), 
	"ID_CONTRATO" NUMBER(5,0), 
	"ID_CONVERSION" NUMBER(10,0), 
	"MONTO_CUOTA" NUMBER(10,2), 
	"N_CUOTA" NUMBER(2,0), 
	"COMISION" NUMBER(3,2), 
	"FECHA_PAGADA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."PERSONA" 
   (	"RUT" VARCHAR2(10 BYTE), 
	"ID_COMUNA" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PATERNO" VARCHAR2(15 BYTE), 
	"MATERNO" VARCHAR2(15 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"MAIL" VARCHAR2(50 BYTE), 
	"FECHA_INGRESO" DATE, 
	"TELEFONO" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPIEDAD
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."PROPIEDAD" 
   (	"ID_PROPIEDAD" NUMBER(5,0), 
	"ID_COMUNA" NUMBER(5,0), 
	"ID_CONSTRUCTORA" NUMBER(6,0), 
	"TIPO_PROPIEDAD" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(400 BYTE), 
	"OPERACION" VARCHAR2(10 BYTE), 
	"DISPONIBLE" CHAR(1 BYTE), 
	"PROYECTO" VARCHAR2(20 BYTE), 
	"METROS_CUADRADOS" NUMBER(5,0), 
	"PRECIO_UF" NUMBER(6,0), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"RUT_PROPIETARIO" VARCHAR2(10 BYTE), 
	"URL_IMAGEN" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPIETARIO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."PROPIETARIO" 
   (	"RUT" VARCHAR2(10 BYTE), 
	"DIA_PAGO" NUMBER(2,0), 
	"FORMA_PAGO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."REGION" 
   (	"ID_REGION" NUMBER(2,0), 
	"NOMBRE_REGION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REGISTROUSUARIO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."REGISTROUSUARIO" 
   (	"RUT" VARCHAR2(12 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"PASSWORD" VARCHAR2(7 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVAPROPIEDAD
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."RESERVAPROPIEDAD" 
   (	"ID_RESERVA" NUMBER(5,0), 
	"ID_PROPIEDAD" NUMBER(5,0), 
	"ID_TIPO_RESERVA" NUMBER(1,0), 
	"ID_SEGURO" NUMBER(5,0), 
	"FECHA" DATE, 
	"RUT" VARCHAR2(10 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEGURO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."SEGURO" 
   (	"ID_SEGURO" NUMBER(5,0), 
	"COMPANIA" VARCHAR2(20 BYTE), 
	"MONTO" NUMBER(6,0), 
	"GLOSA" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."SERVICIO" 
   (	"ID_SERVICIO" NUMBER(6,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"FECHAVIGENCIA" DATE, 
	"VALOR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPORESERVA
--------------------------------------------------------

  CREATE TABLE "IMMOBILIS"."TIPORESERVA" 
   (	"ID_TIPO_RESERVA" NUMBER(1,0), 
	"DESCRIPCION" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BODEGA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_BODEGA" ON "IMMOBILIS"."BODEGA" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CASA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CASA" ON "IMMOBILIS"."CASA" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CLIENTE" ON "IMMOBILIS"."CLIENTE" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COMUNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_COMUNA" ON "IMMOBILIS"."COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONSTRUCTORA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CONSTRUCTORA" ON "IMMOBILIS"."CONSTRUCTORA" ("ID_CONSTRUCTORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONTRATO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CONTRATO" ON "IMMOBILIS"."CONTRATO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONVENIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CONVENIO" ON "IMMOBILIS"."CONVENIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONVERSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_CONVERSION" ON "IMMOBILIS"."CONVERSION" ("ID_CONVERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTAMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_DEPARTAMENTO" ON "IMMOBILIS"."DEPARTAMENTO" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DOCUMENTO_CONTRATO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_DOCUMENTO_CONTRATO" ON "IMMOBILIS"."DOCUMENTO_CONTRATO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DOCUMENTO_RESPALDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_DOCUMENTO_RESPALDO" ON "IMMOBILIS"."DOCUMENTO_RESPALDO" ("ID_CONTRATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLEADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_EMPLEADO" ON "IMMOBILIS"."EMPLEADO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ESTACIONAMIENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_ESTACIONAMIENTO" ON "IMMOBILIS"."ESTACIONAMIENTO" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_OFICINA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_OFICINA" ON "IMMOBILIS"."OFICINA" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PAGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_PAGO" ON "IMMOBILIS"."PAGO" ("ID_VENCIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_PERSONA" ON "IMMOBILIS"."PERSONA" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROPIEDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_PROPIEDAD" ON "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROPIETARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_PROPIETARIO" ON "IMMOBILIS"."PROPIETARIO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REGION
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_REGION" ON "IMMOBILIS"."REGION" ("ID_REGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REGISTROUSUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."REGISTROUSUARIO" ON "IMMOBILIS"."REGISTROUSUARIO" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVAPROPIEDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_RESERVAPROPIEDAD" ON "IMMOBILIS"."RESERVAPROPIEDAD" ("ID_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SEGURO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_SEGURO" ON "IMMOBILIS"."SEGURO" ("ID_SEGURO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SERVICIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_SERVICIO" ON "IMMOBILIS"."SERVICIO" ("ID_SERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TIPORESERVA
--------------------------------------------------------

  CREATE UNIQUE INDEX "IMMOBILIS"."PK_TIPORESERVA" ON "IMMOBILIS"."TIPORESERVA" ("ID_TIPO_RESERVA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BODEGA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."BODEGA" ADD CONSTRAINT "PK_BODEGA" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."BODEGA" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CASA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CASA" ADD CONSTRAINT "PK_CASA" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CASA" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CLIENTE" ADD CONSTRAINT "PK_CLIENTE" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CLIENTE" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."COMUNA" ADD CONSTRAINT "PK_COMUNA" PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."COMUNA" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSTRUCTORA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CONSTRUCTORA" ADD CONSTRAINT "PK_CONSTRUCTORA" PRIMARY KEY ("ID_CONSTRUCTORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CONSTRUCTORA" MODIFY ("ID_CONSTRUCTORA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "PK_CONTRATO" PRIMARY KEY ("ID_CONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONVENIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CONVENIO" ADD CONSTRAINT "PK_CONVENIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CONVENIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONVERSION
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CONVERSION" ADD CONSTRAINT "PK_CONVERSION" PRIMARY KEY ("ID_CONVERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."CONVERSION" MODIFY ("MONEDA_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "IMMOBILIS"."CONVERSION" MODIFY ("MONEDA_ORIGEN" NOT NULL ENABLE);
  ALTER TABLE "IMMOBILIS"."CONVERSION" MODIFY ("FECHA_CONVERSION" NOT NULL ENABLE);
  ALTER TABLE "IMMOBILIS"."CONVERSION" MODIFY ("ID_CONVERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DEPARTAMENTO" ADD CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."DEPARTAMENTO" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTO_CONTRATO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DOCUMENTO_CONTRATO" ADD CONSTRAINT "PK_DOCUMENTO_CONTRATO" PRIMARY KEY ("ID_CONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."DOCUMENTO_CONTRATO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTO_RESPALDO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DOCUMENTO_RESPALDO" ADD CONSTRAINT "PK_DOCUMENTO_RESPALDO" PRIMARY KEY ("ID_CONTRATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."DOCUMENTO_RESPALDO" MODIFY ("ID_CONTRATO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."EMPLEADO" ADD CONSTRAINT "PK_EMPLEADO" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."EMPLEADO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "IMMOBILIS"."EMPLEADO" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTACIONAMIENTO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."ESTACIONAMIENTO" ADD CONSTRAINT "PK_ESTACIONAMIENTO" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."ESTACIONAMIENTO" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFICINA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."OFICINA" ADD CONSTRAINT "PK_OFICINA" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."OFICINA" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAGO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PAGO" ADD CONSTRAINT "PK_PAGO" PRIMARY KEY ("ID_VENCIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."PAGO" MODIFY ("ID_VENCIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PERSONA" ADD CONSTRAINT "PK_PERSONA" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."PERSONA" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROPIEDAD
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PROPIEDAD" ADD CONSTRAINT "PK_PROPIEDAD" PRIMARY KEY ("ID_PROPIEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."PROPIEDAD" MODIFY ("ID_PROPIEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROPIETARIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PROPIETARIO" ADD CONSTRAINT "PK_PROPIETARIO" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."PROPIETARIO" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."REGION" ADD CONSTRAINT "PK_REGION" PRIMARY KEY ("ID_REGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."REGION" MODIFY ("ID_REGION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGISTROUSUARIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."REGISTROUSUARIO" ADD CONSTRAINT "REGISTROUSUARIO" PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."REGISTROUSUARIO" MODIFY ("RUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVAPROPIEDAD
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."RESERVAPROPIEDAD" ADD CONSTRAINT "PK_RESERVAPROPIEDAD" PRIMARY KEY ("ID_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."RESERVAPROPIEDAD" MODIFY ("ID_RESERVA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEGURO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."SEGURO" ADD CONSTRAINT "PK_SEGURO" PRIMARY KEY ("ID_SEGURO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."SEGURO" MODIFY ("ID_SEGURO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."SERVICIO" ADD CONSTRAINT "PK_SERVICIO" PRIMARY KEY ("ID_SERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."SERVICIO" MODIFY ("ID_SERVICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPORESERVA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."TIPORESERVA" ADD CONSTRAINT "PK_TIPORESERVA" PRIMARY KEY ("ID_TIPO_RESERVA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IMMOBILIS"."TIPORESERVA" MODIFY ("ID_TIPO_RESERVA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BODEGA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."BODEGA" ADD CONSTRAINT "FK_BODEGA_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CASA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CASA" ADD CONSTRAINT "FK_CASA_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CLIENTE" ADD CONSTRAINT "FK_CLIENTE_REFERENCE_CONVENIO" FOREIGN KEY ("CONVENIO")
	  REFERENCES "IMMOBILIS"."CONVENIO" ("ID") ENABLE;
  ALTER TABLE "IMMOBILIS"."CLIENTE" ADD CONSTRAINT "FK_CLIENTE_REFERENCE_PERSONA" FOREIGN KEY ("RUT")
	  REFERENCES "IMMOBILIS"."PERSONA" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."COMUNA" ADD CONSTRAINT "FK_COMUNA_REFERENCE_REGION" FOREIGN KEY ("ID_REGION")
	  REFERENCES "IMMOBILIS"."REGION" ("ID_REGION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_REFERENCE_CLIENTE" FOREIGN KEY ("RUT")
	  REFERENCES "IMMOBILIS"."CLIENTE" ("RUT") ENABLE;
  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_REFERENCE_EMPLEADO" FOREIGN KEY ("EMP_RUT")
	  REFERENCES "IMMOBILIS"."EMPLEADO" ("RUT") ENABLE;
  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_REFERENCE_RESERVAP" FOREIGN KEY ("ID_RESERVA")
	  REFERENCES "IMMOBILIS"."RESERVAPROPIEDAD" ("ID_RESERVA") ENABLE;
  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_REFERENCE_SEGURO" FOREIGN KEY ("ID_SEGURO")
	  REFERENCES "IMMOBILIS"."SEGURO" ("ID_SEGURO") ENABLE;
  ALTER TABLE "IMMOBILIS"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_REFERENCE_SERVICIO" FOREIGN KEY ("ID_SERVICIO")
	  REFERENCES "IMMOBILIS"."SERVICIO" ("ID_SERVICIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DEPARTAMENTO" ADD CONSTRAINT "FK_DEPARTAM_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENTO_CONTRATO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DOCUMENTO_CONTRATO" ADD CONSTRAINT "FK_DOCUMENT_REFERENCE_CONTRAT2" FOREIGN KEY ("ID_CONTRATO")
	  REFERENCES "IMMOBILIS"."CONTRATO" ("ID_CONTRATO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENTO_RESPALDO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."DOCUMENTO_RESPALDO" ADD CONSTRAINT "FK_DOCUMENT_REFERENCE_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
	  REFERENCES "IMMOBILIS"."CONTRATO" ("ID_CONTRATO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."EMPLEADO" ADD CONSTRAINT "FK_EMPLEADO_REFERENCE_PERSONA" FOREIGN KEY ("RUT")
	  REFERENCES "IMMOBILIS"."PERSONA" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTACIONAMIENTO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."ESTACIONAMIENTO" ADD CONSTRAINT "FK_ESTACION_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFICINA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."OFICINA" ADD CONSTRAINT "FK_OFICINA_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PAGO" ADD CONSTRAINT "FK_PAGO_REFERENCE_CONTRATO" FOREIGN KEY ("ID_CONTRATO")
	  REFERENCES "IMMOBILIS"."CONTRATO" ("ID_CONTRATO") ENABLE;
  ALTER TABLE "IMMOBILIS"."PAGO" ADD CONSTRAINT "FK_PAGO_REFERENCE_CONVERSI" FOREIGN KEY ("ID_CONVERSION")
	  REFERENCES "IMMOBILIS"."CONVERSION" ("ID_CONVERSION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PERSONA" ADD CONSTRAINT "FK_PERSONA_REFERENCE_COMUNA" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "IMMOBILIS"."COMUNA" ("ID_COMUNA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPIEDAD
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PROPIEDAD" ADD CONSTRAINT "FK_PROPIEDA_REFERENCE_COMUNA" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "IMMOBILIS"."COMUNA" ("ID_COMUNA") ENABLE;
  ALTER TABLE "IMMOBILIS"."PROPIEDAD" ADD CONSTRAINT "FK_PROPIEDA_REFERENCE_CONSTRUC" FOREIGN KEY ("ID_CONSTRUCTORA")
	  REFERENCES "IMMOBILIS"."CONSTRUCTORA" ("ID_CONSTRUCTORA") ENABLE;
  ALTER TABLE "IMMOBILIS"."PROPIEDAD" ADD CONSTRAINT "FK_PROPIEDA_REFERENCE_PROPIETA" FOREIGN KEY ("RUT_PROPIETARIO")
	  REFERENCES "IMMOBILIS"."PROPIETARIO" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPIETARIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."PROPIETARIO" ADD CONSTRAINT "FK_PROPIETA_REFERENCE_PERSONA" FOREIGN KEY ("RUT")
	  REFERENCES "IMMOBILIS"."PERSONA" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGISTROUSUARIO
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."REGISTROUSUARIO" ADD CONSTRAINT "FK_REGISTRO_REFERENCE_PERSONA" FOREIGN KEY ("RUT")
	  REFERENCES "IMMOBILIS"."PERSONA" ("RUT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVAPROPIEDAD
--------------------------------------------------------

  ALTER TABLE "IMMOBILIS"."RESERVAPROPIEDAD" ADD CONSTRAINT "FK_RESERVAP_REFERENCE_PROPIEDA" FOREIGN KEY ("ID_PROPIEDAD")
	  REFERENCES "IMMOBILIS"."PROPIEDAD" ("ID_PROPIEDAD") ENABLE;
  ALTER TABLE "IMMOBILIS"."RESERVAPROPIEDAD" ADD CONSTRAINT "FK_RESERVAP_REFERENCE_SEGURO" FOREIGN KEY ("ID_SEGURO")
	  REFERENCES "IMMOBILIS"."SEGURO" ("ID_SEGURO") ENABLE;
  ALTER TABLE "IMMOBILIS"."RESERVAPROPIEDAD" ADD CONSTRAINT "FK_RESERVAP_REFERENCE_TIPORESE" FOREIGN KEY ("ID_TIPO_RESERVA")
	  REFERENCES "IMMOBILIS"."TIPORESERVA" ("ID_TIPO_RESERVA") ENABLE;
