DELETE FROM DOCUMENTO_CONTRATO;

DELETE FROM DOCUMENTO_RESPALDO;

DELETE FROM BODEGA;

DELETE FROM OFICINA;

DELETE FROM ESTACIONAMIENTO;

DELETE FROM CONTRATO;

DELETE FROM DEPARTAMENTO;

DELETE FROM CLIENTE;

DELETE FROM CASA;

DELETE FROM RESERVAPROPIEDAD;

DELETE FROM PROPIEDAD;

DELETE FROM EMPLEADO;

DELETE FROM PROPIETARIO;

DELETE FROM SERVICIO;

DELETE FROM TIPORESERVA;

DELETE FROM SEGURO;

DELETE FROM REGISTROUSUARIO;

DELETE FROM PERSONA;

DELETE FROM CONVERSION;

DELETE FROM CONVENIO;

DELETE FROM CONSTRUCTORA;

/*==============================================================*/
/* Generate test data for the table "CONSTRUCTORA".             */
/*==============================================================*/
INSERT INTO CONSTRUCTORA (ID_CONSTRUCTORA, NOMBRE) VALUES (1, 'CONSTRUMART');

INSERT INTO CONSTRUCTORA (ID_CONSTRUCTORA, NOMBRE) VALUES (2, 'LOLCOMPANY');

/*==============================================================*/
/* Generate test data for the table "CONVENIO".                 */
/*==============================================================*/
INSERT INTO CONVENIO (ID, NOMBRE, DESCRIPCION, DESCUENTO, FECHA_VIGENCIA) 
VALUES ('0', 'ND', 'SIN CONVENIO', 0, SYSDATE);

INSERT INTO CONVENIO (ID, NOMBRE, DESCRIPCION, DESCUENTO, FECHA_VIGENCIA) 
VALUES ('BBVA', 'BBVA1', 'EJECUTIVOS BANCO', 0.2, SYSDATE);

/*==============================================================*/
/* Generate test data for the table "CONVERSION".               */
/*==============================================================*/
INSERT INTO CONVERSION (ID_CONVERSION, FECHA_CONVERSION, MONEDA_ORIGEN, MONEDA_DESTINO, CONVERSION) 
VALUES (1, SYSDATE, 'UF', 'CLP', 25000);

/*==============================================================*/
/* Generate test data for the table "PERSONA".                  */
/*==============================================================*/
INSERT INTO PERSONA (RUT, ID_COMUNA, NOMBRE, PATERNO, MATERNO, SEXO, DIRECCION, FECHA_NACIMIENTO, MAIL, FECHA_INGRESO, TELEFONO) 
VALUES ('15413610K', 13505, 'SASHA', 'GREY', 'LATIN', 'F', 'SAN JOREGE 1614', SYSDATE, 'MAIL@GMAIL.COM', SYSDATE, '99917072');

INSERT INTO PERSONA (RUT, ID_COMUNA, NOMBRE, PATERNO, MATERNO, SEXO, DIRECCION, FECHA_NACIMIENTO, MAIL, FECHA_INGRESO, TELEFONO) 
VALUES ('146039022', 13601, 'RONALD', 'MCDONALD', 'KING', 'H', 'WASHINGTON 1214', SYSDATE, 'HOLA@KIB.CL', SYSDATE, '+12345678');

INSERT INTO PERSONA (RUT, ID_COMUNA, NOMBRE, PATERNO, MATERNO, SEXO, DIRECCION, FECHA_NACIMIENTO, MAIL, FECHA_INGRESO, TELEFONO) 
VALUES ('63868175', 13601, 'EJECUTIVO', 'EJEC', 'KING', 'H', 'WASHI 1214', SYSDATE, 'EJECUTIVO@KIB.CL', SYSDATE, '+1256468');

/*==============================================================*/
/* Generate test data for the table "REGISTROUSUARIO".          */
/*==============================================================*/
INSERT INTO REGISTROUSUARIO (RUT, ACTIVO, PASSWORD) 
VALUES ('15413610K', 1, '15413');

INSERT INTO REGISTROUSUARIO (RUT, ACTIVO, PASSWORD) 
VALUES ('146039022', 1, '1460');

/*==============================================================*/
/* Generate test data for the table "SEGURO".                   */
/*==============================================================*/
INSERT INTO SEGURO (ID_SEGURO, COMPANIA, MONTO, GLOSA) 
VALUES (1, 'SELECTA', 20000, 'SEGURO MAS NSAL DSETISRFAYQ3E4L N8OAQ3SDVJ0P0WDHFP2HVND5QYVM 9WE8NNL7B EIOILW2S0LQ0F4OW1HV ');

/*==============================================================*/
/* Generate test data for the table "TIPORESERVA".              */
/*==============================================================*/
INSERT INTO TIPORESERVA (ID_TIPO_RESERVA, DESCRIPCION) 
VALUES (1, 'ARRIENDO');

INSERT INTO TIPORESERVA (ID_TIPO_RESERVA, DESCRIPCION)
VALUES (0, 'COMPRA');

/*==============================================================*/
/* Generate test data for the table "SERVICIO".                 */
/*==============================================================*/
INSERT INTO SERVICIO (ID_SERVICIO, DESCRIPCION, FECHAVIGENCIA) 
VALUES (1, 'PINTURA ANUAL', SYSDATE);

INSERT INTO SERVICIO (ID_SERVICIO, DESCRIPCION, FECHAVIGENCIA) 
VALUES (2, 'LIMPIEZA ANUAL', SYSDATE);

/*==============================================================*/
/* Generate test data for the table "PROPIETARIO".              */
/*==============================================================*/
INSERT INTO PROPIETARIO (RUT, DIA_PAGO, FORMA_PAGO) 
VALUES ('146039022', 5, 'EFECTIVO');

/*==============================================================*/
/* Generate test data for the table "EMPLEADO".                 */
/*==============================================================*/
INSERT INTO EMPLEADO (RUT, CARGO, PASSWORD) 
VALUES ('63868175', 'EJECUTIVO', '6386');

/*==============================================================*/
/* Generate test data for the table "PROPIEDAD".                */
/*==============================================================*/
INSERT INTO PROPIEDAD (ID_PROPIEDAD, ID_COMUNA, ID_CONSTRUCTORA, TIPO_PROPIEDAD, DESCRIPCION,                                                                                                                                                                                                                                                                                                                                                  OPERACION, DISPONIBLE, PROYECTO, METROS_CUADRADOS, PRECIO_UF, DIRECCION, RUT_PROPIETARIO) 
VALUES (1, 13128, 1, 'CASA', 'M5KGGEAETN3EU39TQ2YW4 UFJ9A LAK1VR3HNTUBKSKILWUJ88VIB5TV9WVXBLFKOM1KPG5FEWGHDQV3C5YKC9NXWPES5EGLAA3WCG74B690BKSK2 RKYCEKO3S2N5MAGOQBAT6YVCBII897YFPPWEE GYPYI4AXI46ACGLO4EO 4I7E2HWRY9DFIJMDDK009BI B685NU64D2VP L97 P6EQISR LO63HI61P7GLJGAGHSUWMI8TF1IIX8C17G6W4TDEPTRMRYFM9QNFS4KC0HIQBRXCESY56RN9OPEW7U97RS4SSDNHX9EWI  P DMQ2ISM3SY5X51HBBHOOBN7MF6 U8OXP7F7I18EAA0MHKRS2Y1EXS8HCB6I0NSV9KSKQ11LKNF4PO2J7N9', 'COMPRA', 'S', 'JAJADUE', 10, 200, 'LAS ENCINAS 16', '146039022');
INSERT INTO PROPIEDAD (ID_PROPIEDAD, ID_COMUNA, ID_CONSTRUCTORA, TIPO_PROPIEDAD, DESCRIPCION, OPERACION, DISPONIBLE, PROYECTO, METROS_CUADRADOS, PRECIO_UF, DIRECCION, RUT_PROPIETARIO) 
VALUES (2, 10305, 2, 'DEPARTAMENTO', 'M5KGGEAETN3EU39TQ2YW4 UFJ9A LAK1VR3HNTUBKSKILWUJ88VIB5TV9WVXBLFKOM1KPG5FEWGHDQV3C5YKC9NXWPES5EGLAA3WCG74B690BKSK2 RKYCEKO3S2N5MAGOQBAT6YVCBII897YFPPWEE GYPYI4AXI46ACGLO4EO 4I7E2HWRY9DFIJMDDK009BI B685NU64D2VP L97 P6EQISR LO63HI61P7GLJGAGHSUWMI8TF1IIX8C17G6W4TDEPTRMRYFM9QNFS4KC0HIQBRXCESY56RN9OPEW7U97RS4SSDNHX9EWI  P DMQ2ISM3SY5X51HBBHOOBN7MF6 U8OXP7F7I18EAA0MHKRS2Y1EXS8HCB6I0NSV9KSKQ11LKNF4PO2J7N9', 'ARRIENDO', 'N', 'LAS ACACIAS', 1000, 5200, 'LAKSDJALSK 1216', '146039022');
INSERT INTO PROPIEDAD (ID_PROPIEDAD, ID_COMUNA, ID_CONSTRUCTORA, TIPO_PROPIEDAD, DESCRIPCION, OPERACION, DISPONIBLE, PROYECTO, METROS_CUADRADOS, PRECIO_UF, DIRECCION, RUT_PROPIETARIO) 
VALUES (3, 9111, 1, 'OFICINA', 'M5KGGEAETN3EU39TQ2YW4 UFJ9A LAK1VR3HNTUBKSKILWUJ88VIB5TV9WVXBLFKOM1KPG5FEWGHDQV3C5YKC9NXWPES5EGLAA3WCG74B690BKSK2 RKYCEKO3S2N5MAGOQBAT6YVCBII897YFPPWEE GYPYI4AXI46ACGLO4EO 4I7E2HWRY9DFIJMDDK009BI B685NU64D2VP L97 P6EQISR LO63HI61P7GLJGAGHSUWMI8TF1IIX8C17G6W4TDEPTRMRYFM9QNFS4KC0HIQBRXCESY56RN9OPEW7U97RS4SSDNHX9EWI  P DMQ2ISM3SY5X51HBBHOOBN7MF6 U8OXP7F7I18EAA0MHKRS2Y1EXS8HCB6I0NSV9KSKQ11LKNF4PO2J7N9', 'ARRIENDO', 'S', 'CALLE 90N7XYT65O', 200, 1000, 'IMQQ CALLE ASLKDJAS', '146039022');
INSERT INTO PROPIEDAD (ID_PROPIEDAD, ID_COMUNA, ID_CONSTRUCTORA, TIPO_PROPIEDAD, DESCRIPCION, OPERACION, DISPONIBLE, PROYECTO, METROS_CUADRADOS, PRECIO_UF, DIRECCION, RUT_PROPIETARIO) 
VALUES (4, 8308, 2, 'BODEGA', 'M5KGGEAETN3EU39TQ2YW4 UFJ9A LAK1VR3HNTUBKSKILWUJ88VIB5TV9WVXBLFKOM1KPG5FEWGHDQV3C5YKC9NXWPES5EGLAA3WCG74B690BKSK2 RKYCEKO3S2N5MAGOQBAT6YVCBII897YFPPWEE GYPYI4AXI46ACGLO4EO 4I7E2HWRY9DFIJMDDK009BI B685NU64D2VP L97 P6EQISR LO63HI61P7GLJGAGHSUWMI8TF1IIX8C17G6W4TDEPTRMRYFM9QNFS4KC0HIQBRXCESY56RN9OPEW7U97RS4SSDNHX9EWI  P DMQ2ISM3SY5X51HBBHOOBN7MF6 U8OXP7F7I18EAA0MHKRS2Y1EXS8HCB6I0NSV9KSKQ11LKNF4PO2J7N9', 'VENTA', 'S', 'AVENIDA 90N7XYT65O', 1200, 9000, 'CALLE ALLADODELAOTRA 1541', '146039022');
INSERT INTO PROPIEDAD (ID_PROPIEDAD, ID_COMUNA, ID_CONSTRUCTORA, TIPO_PROPIEDAD, DESCRIPCION, OPERACION, DISPONIBLE, PROYECTO, METROS_CUADRADOS, PRECIO_UF, DIRECCION, RUT_PROPIETARIO) 
VALUES (5, 7403, 2, 'ESTACIONAMIENTO', 'M5KGGEAETN3EU39TQ2YW4 UFJ9A LAK1VR3HNTUBKSKILWUJ88VIB5TV9WVXBLFKOM1KPG5FEWGHDQV3C5YKC9NXWPES5EGLAA3WCG74B690BKSK2 RKYCEKO3S2N5MAGOQBAT6YVCBII897YFPPWEE GYPYI4AXI46ACGLO4EO 4I7E2HWRY9DFIJMDDK009BI B685NU64D2VP L97 P6EQISR LO63HI61P7GLJGAGHSUWMI8TF1IIX8C17G6W4TDEPTRMRYFM9QNFS4KC0HIQBRXCESY56RN9OPEW7U97RS4SSDNHX9EWI  P DMQ2ISM3SY5X51HBBHOOBN7MF6 U8OXP7F7I18EAA0MHKRS2Y1EXS8HCB6I0NSV9KSKQ11LKNF4PO2J7N9', 'VENTA', 'S', 'LOTEO 90N7XYT65O', 100, 200, 'SEGOVIA11111', '146039022');

/*==============================================================*/
/* Generate test data for the table "RESERVAPROPIEDAD".         */
/*==============================================================*/
INSERT INTO RESERVAPROPIEDAD (ID_RESERVA, ID_PROPIEDAD, ID_TIPO_RESERVA, ID_SEGURO, FECHA, RUT) 
VALUES (1, 1, 1, 1, SYSDATE, '15413610K');

/*==============================================================*/
/* Generate test data for the table "CASA".                     */
/*==============================================================*/
INSERT INTO CASA (ID_PROPIEDAD, BANO, DORMITORIO, CONJUNTO, METROSCUADRADOSHABITABLES) 
VALUES (1, 2, 3, 'DOMINICA', 200);

/*==============================================================*/
/* Generate test data for the table "CLIENTE".                  */
/*==============================================================*/
INSERT INTO CLIENTE (RUT, CONVENIO) 
VALUES ('15413610K', '0');

/*==============================================================*/
/* Generate test data for the table "DEPARTAMENTO".             */
/*==============================================================*/
INSERT INTO DEPARTAMENTO (ID_PROPIEDAD, EDIFICIO, BANO, DORMITORIO) 
VALUES (2, 'DON TRIZTAN', 2, 5);

/*==============================================================*/
/* Generate test data for the table "CONTRATO".                 */
/*==============================================================*/
INSERT INTO CONTRATO (ID_CONTRATO, ID_RESERVA, DESCUENTO, RUT, EMP_RUT, ID_SERVICIO, ID_SEGURO, FECHA_CONTRATO) 
VALUES (1, 1, 0, '15413610K', '63868175', 1, 1, SYSDATE);

/*==============================================================*/
/* Generate test data for the table "ESTACIONAMIENTO".          */
/*==============================================================*/
INSERT INTO ESTACIONAMIENTO (ID_PROPIEDAD, NIVEL) 
VALUES (5, -1);

/*==============================================================*/
/* Generate test data for the table "OFICINA".                  */
/*==============================================================*/
INSERT INTO OFICINA (ID_PROPIEDAD, PATENTECOMERCIAL) 
VALUES (3, 1234);

/*==============================================================*/
/* Generate test data for the table "BODEGA".                   */
/*==============================================================*/
INSERT INTO BODEGA (ID_PROPIEDAD, ALTURA) 
VALUES (4, 1.5);

/*==============================================================*/
/* Generate test data for the table "DOCUMENTO_RESPALDO".       */
/*==============================================================*/
--INSERT INTO DOCUMENTO_RESPALDO (ID_CONTRATO, URL_AVAL, URL_BOLETA_HONORARIO, URL_CONTRATO_TRABAJO, URL_FOTOCOPIA_CEDULA_IDENTIDAD, URL_LIQUIDACION_SUELDO) VALUES (0, '7 VFXVLO865BMMD54E0F9SOUQUXJUFADW7P69ERTIRRLAU1O7B 3UNM6JAH3BANNY4NU3N6YFG0P3UH4EXN JHO5RKBQQP8R7P2L', '5PTG6ULWDY3NNM8UJ1VUE2ESD4 1RQYO1YT6F7SKDRGUDJJDVBEWQ0EMF60D8P AA1FJ8NK2627WAL2CLMNHJCJLYXN8LYHQCW4G', '11ITU08GMH JIJ490WT4YM9I8IFBJRHDQ1Y8C0JRYN3RIWIIO6TPCTIQXBIB539BJ4RRISBL9FUU7VMYIJRSWD2WW Y6BQDS6HJY', '4BU6YSEQAVGXW2MWDCVKQYQ84PWVQ4JBSTMDVMJ97K46NOXKC6YSGGHXHC03NTND4U9I6GNFF0 4W2XDDJK8GGGQBA4NU5FRL7LG', 'JRU6AEFMBNHXUE1 MRJ4EGR5NH32L1JMYMWJYB43UO4V4 XQ4WCMF1MRPWH EP8YW27INKSHX52VFTWPL83S GJ77C468UWX5RT7');

/*==============================================================*/
/* Generate test data for the table "DOCUMENTO_CONTRATO".       */
/*==============================================================*/
--INSERT INTO DOCUMENTO_CONTRATO (ID_CONTRATO, URL_BANCO, URL_CONSERVADOR_BIENES_RAICES, URL_NOTARIA, URL_TASACION) VALUES (0, '5LYPSL4UN7JIJRLI7C5GYI08FO3U FEIWUPRLQ5PMHK6Q5UUK96P A3SG3NXTKNCFBOAHUIF59BTHQALOP84Q9GIWLUHAP5IMUQ0', 'QAGI48108ANUPG5J23M7HEBQXHCYW8MSUYP713UNM82CGEMY0VEKHON7G 2DEC2VE6AI3KRUFF3RDDCRS82 YRCOPXLAX3LQ6XO9', '3GR2LCPFL9SKRFDNJVS8QHKXYCQ65NT1IKN07W9HU2FBF4BKIC99PD2DI3W8CBX7HP7OJMIXLPL6FKHGWJ DXVJFEBD72GRXUQ2E', ' INGX6LNMLPWAT2HWRWP1 DSN4F30KTN368JKJKHYGC7YMITADFMG7 SQVDH44WCMMAIWTJOM12HUD9UUJSCF0AGYTLKWDOLFJ6F');

